language: python

cache:
  directories:
  - "~/.platformio"

install:
- pip install -U platformio

env:
- BOARD=uno

script:
  - "echo $PWD"
  - "echo $HOME"
  - "ls $PWD"
  - platformio ci --board=$BOARD --lib=$PWD/Arduino\ Code/h20Shield_pde $PWD/Arduino\ Code/h20Shield_pde/h20Shield_pde.pde
  
notifications:
  email:
    on_success: change
    on_failure: change